# Generated by Django 5.0 on 2025-04-01 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='one_time_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasword_expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 18, 13, 3, 867261, tzinfo=datetime.timezone.utc)),
        ),
    ]
